# Generated by Django 2.2.5 on 2019-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=3000, verbose_name='Описание')),
                ('status', models.TextField(blank=True, default='new', max_length=200, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
            ],
        ),
    ]
